/*
*
* ALL DEFINES TO USE "int WINDOW_WIDTH" NAMING CONVENTIONS
* THIS FILE IS FOR ALL ASSETS DEFINE FILE PATHS
*
*/

#pragma once

#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 900

#define SPLASHSCREEN_TIME 3.0f

#define SPLASHSCREEN_TEXTURE "Assets/UI Assets/Container Beige.png"

#define MAIN_MENU_BUTTON_TEXTURE "Assets/UI Assets/Button Beige.png"


// BUTTON PROPERTIES
#define BUTTON_SCALE 50.f

