/*
*
* ALL DEFINES TO USE "int WINDOW_WIDTH" NAMING CONVENTIONS
* THIS FILE IS FOR ALL ASSETS DEFINE FILE PATHS
*
*/

#pragma once


#define WINDOW_WIDTH 1600
#define WINDOW_HEIGHT 900

#define SPLASHSCREEN_TIME 3.0f


// FILE PATHS
#define SPLASHSCREEN_TEXTURE "Assets/UI Assets/Container Beige.png"

#define MAIN_MENU_BUTTON_TEXTURE "Assets/UI Assets/Button Beige.png"

#define FONT "Assets/Font/Kenney Future Narrow.ttf"


// BUTTON PROPERTIES
#define BUTTON_SCALE 1.5f
#define TEXT_SCALE 24

// PARTICLE COUNT
#define PARTICLE_COUNT 1000

#define M_PI 3.14159265358979323846
